apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockydev-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rockydev-app
  template:
    metadata:
      labels:
        app: rockydev-app
    spec:
      containers:
        - name: rockydev-app
          image: sebastiandev1/rockydev:v2
          command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
          ports:
            - containerPort: 8080
